server:
  port: 8764
spring:
  application:
    name: eurekaclient
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
---
spring:
    zipkin:
        base-url: http://localhost:9411
        sender:
            type: web
    sleuth:
        sampler:
          probability : 1